/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package onlinebankwebserviceapiclient;

import com.google.gson.Gson;
import com.mycompany.onlinebankwebserviceapi.model.Customer;
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.net.HttpURLConnection;
import java.net.MalformedURLException;
import java.net.URL;
import com.google.gson.annotations.SerializedName;
import com.mycompany.onlinebankwebserviceapi.model.Transaction;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.time.LocalDate;
import java.util.List;

/**
 *
 * @author carlosneia
 */
public class RunnerGUI extends javax.swing.JFrame {

    /**
     * Creates new form RunnerGUI
     */
    public RunnerGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        showAllCustomersBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        displayTa = new javax.swing.JTextArea();
        getCustomerByIdBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        getCustomerByIdTf = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        getAccountByIdTf = new javax.swing.JTextField();
        getAccountByIdBtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        accDetailsTf = new javax.swing.JTextField();
        accDetailsBtn = new javax.swing.JButton();
        showAllTransactionsBtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        transferFromTf = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        transferToTf = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        transferAmountTf = new javax.swing.JTextField();
        transferBtn = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        ShowAllAccountsBtn = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        loginTf = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        passwordTf = new javax.swing.JTextField();
        loginBtn = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        addNameTf = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        addAddressTf = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        addEmailTf = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        addLoginTf = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        addPasswordTf = new javax.swing.JTextField();
        addCustomerBtn = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        newAccountTf = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        newAccountBtn = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        transactionCb = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        transactionAccTf = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        transactionAmountTf = new javax.swing.JTextField();
        transactionBtn = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        transactionDescriptionTf = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        showAllCustomersBtn.setText("Show All Customers");
        showAllCustomersBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showAllCustomersBtnActionPerformed(evt);
            }
        });

        displayTa.setColumns(20);
        displayTa.setRows(5);
        jScrollPane1.setViewportView(displayTa);

        getCustomerByIdBtn.setText("Search");
        getCustomerByIdBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getCustomerByIdBtnActionPerformed(evt);
            }
        });

        jLabel1.setText("Customer By Id:");

        jLabel2.setText("Accounts By Id:");

        getAccountByIdBtn.setText("Search");
        getAccountByIdBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getAccountByIdBtnActionPerformed(evt);
            }
        });

        jLabel3.setText("Acc Details By Acc Number:");

        accDetailsBtn.setText("Search");
        accDetailsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accDetailsBtnActionPerformed(evt);
            }
        });

        showAllTransactionsBtn.setText("Show All Transactions");
        showAllTransactionsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showAllTransactionsBtnActionPerformed(evt);
            }
        });

        jLabel4.setText("Transfer From: ");

        jLabel5.setText("To:");

        jLabel6.setText("Amount:");

        transferBtn.setText("Transfer");
        transferBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transferBtnActionPerformed(evt);
            }
        });

        ShowAllAccountsBtn.setText("Show All Accounts");
        ShowAllAccountsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowAllAccountsBtnActionPerformed(evt);
            }
        });

        jLabel7.setText("User Login:");

        jLabel8.setText("Password:");

        loginBtn.setText("login");
        loginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBtnActionPerformed(evt);
            }
        });

        jLabel9.setText("Add New Customer: ");

        jLabel10.setText("Name:");

        jLabel11.setText("Address:");

        jLabel12.setText("Email:");

        addEmailTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addEmailTfActionPerformed(evt);
            }
        });

        jLabel13.setText("Login:");

        jLabel14.setText("Password:");

        addPasswordTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPasswordTfActionPerformed(evt);
            }
        });

        addCustomerBtn.setText("Create Customer");
        addCustomerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCustomerBtnActionPerformed(evt);
            }
        });

        jLabel15.setText("Insert the login to create new account: ");

        newAccountBtn.setText("OK");
        newAccountBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newAccountBtnActionPerformed(evt);
            }
        });

        jLabel17.setText("Transaction:");

        transactionCb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select...", "Credit", "Debit" }));
        transactionCb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transactionCbActionPerformed(evt);
            }
        });

        jLabel18.setText("Acc Number:");

        jLabel19.setText("Amount: ");

        transactionBtn.setText("OK");
        transactionBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transactionBtnActionPerformed(evt);
            }
        });

        jLabel20.setText("Description:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 474, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(transferBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel1))
                                    .addGap(81, 81, 81)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(getAccountByIdTf, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(accDetailsTf, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(getCustomerByIdTf, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(getAccountByIdBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                            .addComponent(getCustomerByIdBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(accDetailsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel7)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(loginTf, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel8)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(passwordTf, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(loginBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 486, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(showAllTransactionsBtn)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(transferFromTf, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jLabel5)
                                    .addGap(12, 12, 12)
                                    .addComponent(transferToTf, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel6)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(transferAmountTf, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 486, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(14, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel12))
                                .addGap(24, 24, 24)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(addNameTf, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                                    .addComponent(addEmailTf))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addGap(1, 1, 1)
                                .addComponent(addPasswordTf, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(90, 90, 90)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(addCustomerBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                            .addComponent(addAddressTf, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addLoginTf, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(37, 37, 37))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(newAccountTf, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(newAccountBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel16))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 486, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel17)
                                    .addComponent(jLabel19))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(transactionCb, 0, 121, Short.MAX_VALUE)
                                    .addComponent(transactionAmountTf))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel18)
                                    .addComponent(jLabel20))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(transactionAccTf)
                                    .addComponent(transactionDescriptionTf, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE))))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(showAllCustomersBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ShowAllAccountsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(transactionBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(showAllCustomersBtn)
                    .addComponent(ShowAllAccountsBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(getCustomerByIdBtn)
                    .addComponent(jLabel1)
                    .addComponent(getCustomerByIdTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(getAccountByIdTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(getAccountByIdBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(accDetailsTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(accDetailsBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(loginTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(passwordTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(loginBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(transferFromTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(transferToTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(transferAmountTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(transferBtn)
                    .addComponent(showAllTransactionsBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(addNameTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(addAddressTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(addEmailTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(addLoginTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(addPasswordTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addCustomerBtn))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(newAccountTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(newAccountBtn))
                .addGap(4, 4, 4)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(transactionCb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18)
                    .addComponent(transactionAccTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(transactionAmountTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20)
                    .addComponent(transactionDescriptionTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(transactionBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    GETRequestes cm = new GETRequestes();

    private void showAllCustomersBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showAllCustomersBtnActionPerformed

        displayTa.setText("");

        for (int i = 0; i < cm.getAllCustomers().size(); i++) {
            String name = cm.getAllCustomers().get(i).getName();
            String address = cm.getAllCustomers().get(i).getAddress();
            String email = cm.getAllCustomers().get(i).getEmail();
            String login = cm.getAllCustomers().get(i).getLogin();
            String password = cm.getAllCustomers().get(i).getPassword();

            displayTa.append("Name: " + name
                    + "\nAddress: " + address
                    + "\nEmail: " + email
                    + "\nLogin: " + login
                    + "\nPassword: " + password + "\n\n");
        }
    }//GEN-LAST:event_showAllCustomersBtnActionPerformed

    //Search customer's details by customer ID and Display it
    private void getCustomerByIdBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getCustomerByIdBtnActionPerformed
        displayTa.setText("");
        String customerId = getCustomerByIdTf.getText();
        String name = cm.getCustomerByID(customerId).getName();
        String address = cm.getCustomerByID(customerId).getAddress();
        String email = cm.getCustomerByID(customerId).getEmail();
        String login = cm.getCustomerByID(customerId).getLogin();
        String password = cm.getCustomerByID(customerId).getPassword();

        displayTa.append("Name: " + name
                + "\nAddress: " + address
                + "\nEmail: " + email
                + "\nLogin: " + login
                + "\nPassword: " + password);

        getCustomerByIdTf.setText("");
    }//GEN-LAST:event_getCustomerByIdBtnActionPerformed

    private void getAccountByIdBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getAccountByIdBtnActionPerformed
        displayTa.setText("");

        String login = getAccountByIdTf.getText();

        for (int i = 0; i < cm.getAllAccountsForCustomer(login).size(); i++) {
            int sortCode = cm.getAllAccountsForCustomer(login).get(i).getSortCode();
            int accNumber = cm.getAllAccountsForCustomer(login).get(i).getAccountNumber();
            double balance = cm.getAllAccountsForCustomer(login).get(i).getBalance();
            String customerId = cm.getAllAccountsForCustomer(login).get(i).getCustomerId();

            displayTa.append("Sort Code: " + sortCode
                    + "\nAccount Number: " + accNumber
                    + "\nBalance: " + balance
                    + "\nCustomer Id: " + customerId + "\n\n");

            getAccountByIdTf.setText("");
        }


    }//GEN-LAST:event_getAccountByIdBtnActionPerformed

    private void accDetailsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accDetailsBtnActionPerformed
        displayTa.setText("");

        int accNumber = Integer.parseInt(accDetailsTf.getText());

        int sortCode = cm.getAccountsDetails(accNumber).getSortCode();
        int myAccNumber = cm.getAccountsDetails(accNumber).getAccountNumber();
        double balance = cm.getAccountsDetails(accNumber).getBalance();
        String customerId = cm.getAccountsDetails(accNumber).getCustomerId();

        displayTa.append("Sort Code: " + sortCode
                + "\nAccount Number: " + accNumber
                + "\nBalance: " + balance
                + "\nCustomer Id: " + customerId);

        accDetailsTf.setText("");

        accDetailsTf.setText("");
    }//GEN-LAST:event_accDetailsBtnActionPerformed

    private void showAllTransactionsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showAllTransactionsBtnActionPerformed
        displayTa.setText("");
        for (int i = 0; i < cm.getAllTransactions().size(); i++) {
            int transactionType = cm.getAllTransactions().get(i).getTransactionType();
            LocalDate date = cm.getAllTransactions().get(i).getDate();
            String description = cm.getAllTransactions().get(i).getDescription();
            double postTransactionBalance = cm.getAllTransactions().get(i).getPostTransactionBalance();
            int accountNumber = cm.getAllTransactions().get(i).getAccountNumber();
            double amount = cm.getAllTransactions().get(i).getAmount();

            displayTa.append("Transaction Type: " + transactionType
                    + "\nDate: " + date
                    + "\nDescription: " + description
                    + "\nPost Transaction Balance: " + postTransactionBalance
                    + "\nAccount Number: " + accountNumber
                    + "\nAmount: " + amount + "\n\n");

        }
    }//GEN-LAST:event_showAllTransactionsBtnActionPerformed

    private void transferBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transferBtnActionPerformed
        displayTa.setText("");

        displayTa.append(
                cm.makeTransfer(Integer.parseInt(transferFromTf.getText()),
                        Integer.parseInt(transferToTf.getText()),
                        Integer.parseInt(transferAmountTf.getText())));

        transferFromTf.setText("");
        transferToTf.setText("");
        transferAmountTf.setText("");
    }//GEN-LAST:event_transferBtnActionPerformed

    private void ShowAllAccountsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowAllAccountsBtnActionPerformed

        displayTa.setText("");

        for (int i = 0; i < cm.getAllAccounts().size(); i++) {
            int sortCode = cm.getAllAccounts().get(i).getSortCode();
            int accNumber = cm.getAllAccounts().get(i).getAccountNumber();
            double balance = cm.getAllAccounts().get(i).getBalance();
            String customerId = cm.getAllAccounts().get(i).getCustomerId();

            displayTa.append("Sort Code: " + sortCode
                    + "\nAccount Number: " + accNumber
                    + "\nBalance: " + balance
                    + "\nCustomer Id: " + customerId + "\n\n");

        }
    }//GEN-LAST:event_ShowAllAccountsBtnActionPerformed

    private void loginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBtnActionPerformed

        displayTa.setText("");
        displayTa.append(
                cm.login(loginTf.getText(), passwordTf.getText()));
        
        loginTf.setText("");
        passwordTf.setText("");

    }//GEN-LAST:event_loginBtnActionPerformed

    private void addEmailTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addEmailTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addEmailTfActionPerformed

    POSTRequests pr = new POSTRequests();


    private void addCustomerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCustomerBtnActionPerformed

        displayTa.setText("");
        Customer c = new Customer();
        c.setName(addNameTf.getText());
        c.setAddress(addAddressTf.getText());
        c.setEmail(addEmailTf.getText());
        c.setLogin(addLoginTf.getText());
        c.setPassword(addPasswordTf.getText());

        displayTa.append(pr.newCustomer(c));

        addNameTf.setText("");
        addAddressTf.setText("");
        addEmailTf.setText("");
        addLoginTf.setText("");
        addPasswordTf.setText("");
    }//GEN-LAST:event_addCustomerBtnActionPerformed

    private void newAccountBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newAccountBtnActionPerformed
        
        displayTa.setText("");
        displayTa.append(pr.newAccount(newAccountTf.getText()));
        newAccountTf.setText("");
    }//GEN-LAST:event_newAccountBtnActionPerformed
    
    String [] options= {"Select...", "Debit", "Credit"};
    
            
            
    private void transactionCbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transactionCbActionPerformed
        
    }//GEN-LAST:event_transactionCbActionPerformed

    private void addPasswordTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPasswordTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addPasswordTfActionPerformed

    private void transactionBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transactionBtnActionPerformed
        displayTa.setText("");
        Transaction t = new Transaction();
        t.setAccountNumber(Integer.parseInt(transactionAccTf.getText()));
        t.setAmount(Double.parseDouble(transactionAmountTf.getText()));
        t.setDescription(transactionDescriptionTf.getText());
        if (transactionCb.getSelectedIndex() == 1){
            displayTa.append(pr.newCreditTransaction(t));
        } else if (transactionCb.getSelectedIndex() == 2){
            displayTa.append(pr.newDebitTransaction(t));
        }else{
           
        }
        transactionAccTf.setText("");
        transactionAmountTf.setText("");
        transactionDescriptionTf.setText("");
        
        
    }//GEN-LAST:event_transactionBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RunnerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RunnerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RunnerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RunnerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RunnerGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ShowAllAccountsBtn;
    private javax.swing.JButton accDetailsBtn;
    private javax.swing.JTextField accDetailsTf;
    private javax.swing.JTextField addAddressTf;
    private javax.swing.JButton addCustomerBtn;
    private javax.swing.JTextField addEmailTf;
    private javax.swing.JTextField addLoginTf;
    private javax.swing.JTextField addNameTf;
    private javax.swing.JTextField addPasswordTf;
    private javax.swing.JTextArea displayTa;
    private javax.swing.JButton getAccountByIdBtn;
    private javax.swing.JTextField getAccountByIdTf;
    private javax.swing.JButton getCustomerByIdBtn;
    private javax.swing.JTextField getCustomerByIdTf;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JButton loginBtn;
    private javax.swing.JTextField loginTf;
    private javax.swing.JButton newAccountBtn;
    private javax.swing.JTextField newAccountTf;
    private javax.swing.JTextField passwordTf;
    private javax.swing.JButton showAllCustomersBtn;
    private javax.swing.JButton showAllTransactionsBtn;
    private javax.swing.JTextField transactionAccTf;
    private javax.swing.JTextField transactionAmountTf;
    private javax.swing.JButton transactionBtn;
    private javax.swing.JComboBox<String> transactionCb;
    private javax.swing.JTextField transactionDescriptionTf;
    private javax.swing.JTextField transferAmountTf;
    private javax.swing.JButton transferBtn;
    private javax.swing.JTextField transferFromTf;
    private javax.swing.JTextField transferToTf;
    // End of variables declaration//GEN-END:variables
}
